title: Raymond K. Zhao
description: CTO & Co-founder@ExeQuantum | Ex Postdoc@CSIRO's Data61
show_downloads: false
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github:
  repository_url: https://gitlab.com/raykzhao
